package org.sumaciudadana.affidavit.entity;

// Generated 06/07/2012 11:12:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BelongingType generated by hbm2java
 */
@Entity
@Table(name = "belonging_type", catalog = "sumaciudadana")
public class BelongingType  {

	private Integer idbelongingTypes;
	private String desBelongingType;
	private Set<Belonging> belongings = new HashSet<Belonging>(0);

	public BelongingType() {
	}

	public BelongingType(String desBelongingType, Set<Belonging> belongings) {
		this.desBelongingType = desBelongingType;
		this.belongings = belongings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idbelonging_types", unique = true, nullable = false)
	public Integer getIdbelongingTypes() {
		return this.idbelongingTypes;
	}

	public void setIdbelongingTypes(Integer idbelongingTypes) {
		this.idbelongingTypes = idbelongingTypes;
	}

	@Column(name = "des_belonging_type", length = 45)
	public String getDesBelongingType() {
		return this.desBelongingType;
	}

	public void setDesBelongingType(String desBelongingType) {
		this.desBelongingType = desBelongingType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "belongingType")
	public Set<Belonging> getBelongings() {
		return this.belongings;
	}

	public void setBelongings(Set<Belonging> belongings) {
		this.belongings = belongings;
	}

}
