package org.sumaciudadana.affidavit.entity;

// Generated 06/07/2012 11:12:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name = "complaint", catalog = "sumaciudadana")
public class Complaint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1075221341773135109L;
	
	private Integer idcomplaint;
	private Pservant pservant;
	private String comDescription;
	private byte[] comFile;

	public Complaint() {
	}

	public Complaint(Pservant pservant) {
		this.pservant = pservant;
	}

	public Complaint(Pservant pservant, String comDescription, byte[] comFile) {
		this.pservant = pservant;
		this.comDescription = comDescription;
		this.comFile = comFile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcomplaint", unique = true, nullable = false)
	public Integer getIdcomplaint() {
		return this.idcomplaint;
	}

	public void setIdcomplaint(Integer idcomplaint) {
		this.idcomplaint = idcomplaint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpservant", nullable = false)
	public Pservant getPservant() {
		return this.pservant;
	}

	public void setPservant(Pservant pservant) {
		this.pservant = pservant;
	}

	@Column(name = "com_description", length = 200)
	public String getComDescription() {
		return this.comDescription;
	}

	public void setComDescription(String comDescription) {
		this.comDescription = comDescription;
	}

	@Column(name = "com_file")
	public byte[] getComFile() {
		return this.comFile;
	}

	public void setComFile(byte[] comFile) {
		this.comFile = comFile;
	}

}
