package org.sumaciudadana.affidavit.entity;

// Generated 06/07/2012 11:12:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "sumaciudadana")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3544953114299594102L;
	
	private Integer iduser;
	private String username;
	private String password;
	private String UFirstname;
	private String UFirstsurname;
	private String USecondsurname;
	private String UTelephone;
	private String UAddress;
	private String UEmail;
	private Character UStatus;
	private String userCreate;
	private Date dateCreate;
	private String userModify;
	private Date dateModify;

	public User() {
	}

	public User(String username, String password, String UFirstname,
			String UFirstsurname, String USecondsurname, String UTelephone,
			String UAddress, String UEmail, Character UStatus,
			String userCreate, Date dateCreate, String userModify,
			Date dateModify) {
		this.username = username;
		this.password = password;
		this.UFirstname = UFirstname;
		this.UFirstsurname = UFirstsurname;
		this.USecondsurname = USecondsurname;
		this.UTelephone = UTelephone;
		this.UAddress = UAddress;
		this.UEmail = UEmail;
		this.UStatus = UStatus;
		this.userCreate = userCreate;
		this.dateCreate = dateCreate;
		this.userModify = userModify;
		this.dateModify = dateModify;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iduser", unique = true, nullable = false)
	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "u_firstname", length = 45)
	public String getUFirstname() {
		return this.UFirstname;
	}

	public void setUFirstname(String UFirstname) {
		this.UFirstname = UFirstname;
	}

	@Column(name = "u_firstsurname", length = 45)
	public String getUFirstsurname() {
		return this.UFirstsurname;
	}

	public void setUFirstsurname(String UFirstsurname) {
		this.UFirstsurname = UFirstsurname;
	}

	@Column(name = "u_secondsurname", length = 45)
	public String getUSecondsurname() {
		return this.USecondsurname;
	}

	public void setUSecondsurname(String USecondsurname) {
		this.USecondsurname = USecondsurname;
	}

	@Column(name = "u_telephone", length = 45)
	public String getUTelephone() {
		return this.UTelephone;
	}

	public void setUTelephone(String UTelephone) {
		this.UTelephone = UTelephone;
	}

	@Column(name = "u_address", length = 45)
	public String getUAddress() {
		return this.UAddress;
	}

	public void setUAddress(String UAddress) {
		this.UAddress = UAddress;
	}

	@Column(name = "u_email", length = 45)
	public String getUEmail() {
		return this.UEmail;
	}

	public void setUEmail(String UEmail) {
		this.UEmail = UEmail;
	}

	@Column(name = "u_status", length = 1)
	public Character getUStatus() {
		return this.UStatus;
	}

	public void setUStatus(Character UStatus) {
		this.UStatus = UStatus;
	}

	@Column(name = "user_create", length = 45)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_create", length = 19)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "user_modify", length = 45)
	public String getUserModify() {
		return this.userModify;
	}

	public void setUserModify(String userModify) {
		this.userModify = userModify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modify", length = 19)
	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

}
